// Generated by CoffeeScript 2.7.0
var ans, cAns, check, correct, correctAns, n1, n2, resetTimer, startTimer, stat, timeLeft, timeRemaining, timer, updateNums, wAns, wrong, wrongAns;

n1 = document.getElementById('number1');

n2 = document.getElementById('number2');

ans = document.getElementById('answer');

stat = document.getElementById('stat');

correctAns = document.getElementById('correct-answers');

wrongAns = document.getElementById('wrong-answers');

timeLeft = document.getElementById('time-left');

timeRemaining = 5;

cAns = 0;

wAns = 0;

timer = null;

updateNums = function() {
  n1.textContent = Math.floor(Math.random() * 12);
  n2.textContent = Math.floor(Math.random() * 12);
  return answer.value = '';
};

correct = function() {
  stat.textContent = "Good job!";
  setTimeout(function() {
    return stat.textContent = "Answer the question.";
  }, 1000);
  timeRemaining = 5;
  resetTimer();
  startTimer();
  cAns++;
  correctAns.textContent = cAns;
  return updateNums();
};

wrong = function() {
  stat.textContent = "Try again.";
  setTimeout(function() {
    return stat.textContent = "Answer the question.";
  }, 1000);
  timeRemaining = 5;
  resetTimer();
  startTimer();
  wAns++;
  wrongAns.textContent = wAns;
  return updateNums();
};

check = function() {
  if ((Number(n1.textContent * n2.textContent)) === Number(answer.value)) {
    return correct();
  } else {
    return wrong();
  }
};

resetTimer = function() {
  return clearInterval(timer);
};

startTimer = function() {
  return timer = setInterval(function() {
    timeRemaining--;
    timeLeft.textContent = timeRemaining;
    if (timeRemaining <= 0) {
      return check();
    }
  }, 1000);
};

startTimer();

answer.addEventListener('keydown', function(event) {
  if (event.key === 'Enter') {
    return check();
  }
});
