// Generated by CoffeeScript 2.7.0
var ans, cAns, ch, check, correct, correctAns, del, eight, five, four, n1, n2, nine, one, resetTimer, seven, six, startTimer, stat, three, timeLeft, timeRemaining, timer, two, updateNums, wAns, wrong, wrongAns, zero;

n1 = document.getElementById('number1');

n2 = document.getElementById('number2');

ans = document.getElementById('answer');

stat = document.getElementById('stat');

one = document.getElementById('1');

two = document.getElementById('2');

three = document.getElementById('3');

four = document.getElementById('4');

five = document.getElementById('5');

six = document.getElementById('6');

seven = document.getElementById('7');

eight = document.getElementById('8');

nine = document.getElementById('9');

zero = document.getElementById('0');

ch = document.getElementById('check');

del = document.getElementById('del');

correctAns = document.getElementById('correct-answers');

wrongAns = document.getElementById('wrong-answers');

timeLeft = document.getElementById('time-left');

timeRemaining = 7;

cAns = 0;

wAns = 0;

timer = null;

updateNums = function() {
  if (n1 != null) {
    n1.textContent = Math.floor(Math.random() * 12);
  }
  if (n2 != null) {
    n2.textContent = Math.floor(Math.random() * 12);
  }
  return typeof answer !== "undefined" && answer !== null ? answer.value = '' : void 0;
};

correct = function() {
  if (stat != null) {
    stat.textContent = "Good job!";
  }
  setTimeout(function() {
    return stat != null ? stat.textContent = "Answer the question." : void 0;
  }, 1000);
  timeRemaining = 7;
  resetTimer();
  startTimer();
  cAns++;
  if (correctAns != null) {
    correctAns.textContent = cAns;
  }
  return updateNums();
};

wrong = function() {
  if (stat != null) {
    stat.textContent = "Try again.";
  }
  setTimeout(function() {
    return stat != null ? stat.textContent = "Answer the question." : void 0;
  }, 1000);
  timeRemaining = 7;
  resetTimer();
  startTimer();
  wAns++;
  if (wrongAns != null) {
    wrongAns.textContent = wAns;
  }
  return typeof answer !== "undefined" && answer !== null ? answer.value = '' : void 0;
};

check = function() {
  if ((Number((n1 != null ? n1.textContent : void 0) * (n2 != null ? n2.textContent : void 0))) === Number(typeof answer !== "undefined" && answer !== null ? answer.value : void 0)) {
    return correct();
  } else {
    return wrong();
  }
};

resetTimer = function() {
  return clearInterval(timer);
};

startTimer = function() {
  return timer = setInterval(function() {
    timeRemaining--;
    if (timeLeft != null) {
      timeLeft.textContent = timeRemaining;
    }
    if (timeRemaining <= 0) {
      return check();
    }
  }, 1000);
};

startTimer();

if (typeof answer !== "undefined" && answer !== null) {
  answer.addEventListener('keydown', function(event) {
    if (event.key === 'Enter') {
      return check();
    }
  });
}

if (one != null) {
  one.addEventListener('click', function() {
    return typeof answer !== "undefined" && answer !== null ? answer.value += 1 : void 0;
  });
}

if (two != null) {
  two.addEventListener('click', function() {
    return typeof answer !== "undefined" && answer !== null ? answer.value += 2 : void 0;
  });
}

if (three != null) {
  three.addEventListener('click', function() {
    return typeof answer !== "undefined" && answer !== null ? answer.value += 3 : void 0;
  });
}

if (four != null) {
  four.addEventListener('click', function() {
    return typeof answer !== "undefined" && answer !== null ? answer.value += 4 : void 0;
  });
}

if (five != null) {
  five.addEventListener('click', function() {
    return typeof answer !== "undefined" && answer !== null ? answer.value += 5 : void 0;
  });
}

if (six != null) {
  six.addEventListener('click', function() {
    return typeof answer !== "undefined" && answer !== null ? answer.value += 6 : void 0;
  });
}

if (seven != null) {
  seven.addEventListener('click', function() {
    return typeof answer !== "undefined" && answer !== null ? answer.value += 7 : void 0;
  });
}

if (eight != null) {
  eight.addEventListener('click', function() {
    return typeof answer !== "undefined" && answer !== null ? answer.value += 8 : void 0;
  });
}

if (nine != null) {
  nine.addEventListener('click', function() {
    return typeof answer !== "undefined" && answer !== null ? answer.value += 9 : void 0;
  });
}

if (zero != null) {
  zero.addEventListener('click', function() {
    return typeof answer !== "undefined" && answer !== null ? answer.value += 0 : void 0;
  });
}

if (ch != null) {
  ch.addEventListener('click', function() {
    return check();
  });
}

if (del != null) {
  del.addEventListener('click', function() {
    return typeof answer !== "undefined" && answer !== null ? answer.value = typeof answer !== "undefined" && answer !== null ? answer.value.slice(0, -1) : void 0 : void 0;
  });
}
